"""
LogicalSchemaTransformer: Converts physical MapRegister/Metadata into logical entity definitions.
Abstracts away backend-specific details (SQL tables, MongoDB collections, storage placement).
"""
from typing import Dict, Any, List, Set, Optional
from utils.log import logger


class LogicalField:
    """Represents a logical field in an entity."""
    
    def __init__(self, name: str, logical_type: str):
        self.name = name
        self.logical_type = logical_type  # Mapped from Metadata.type
        self.is_key = False
        self.is_required = False
        self.is_auto_generated = False
        self.sample_value: Any = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize field to dictionary."""
        return {
            "name": self.name,
            "logical_type": self.logical_type,
            "is_key": self.is_key,
            "is_required": self.is_required,
            "is_auto_generated": self.is_auto_generated,
            "sample_value": self.sample_value,
        }


class LogicalEntity:
    """Represents a logical entity (table) with abstracted schema."""
    
    def __init__(self, entity_name: str, table_name: str):
        self.entity_name = entity_name  # User-friendly name (e.g., "User")
        self.table_name = table_name  # Internal name (hidden from frontend)
        self.fields: Dict[str, LogicalField] = {}
        self.relationships: List[Dict[str, Any]] = []
        self.record_count = 0
        self.request_count = 0
    
    def add_field(self, field: LogicalField) -> None:
        """Add a field to the entity."""
        self.fields[field.name] = field
    
    def add_relationship(self, related_entity: str, relationship_type: str) -> None:
        """Record a relationship to another entity."""
        rel = {
            "entity": related_entity,
            "type": relationship_type,  # one_to_one, one_to_many, many_to_many
        }
        if rel not in self.relationships:
            self.relationships.append(rel)
    
    def to_dict(self, include_internal: bool = False) -> Dict[str, Any]:
        """
        Serialize entity to dictionary.
        
        Args:
            include_internal: If True, include table_name (for internal use only)
        """
        result: Dict[str, Any] = {
            "entity_name": self.entity_name,
            "fields": [f.to_dict() for f in self.fields.values()],
            "relationships": self.relationships,
            "record_count": self.record_count,
            "request_count": self.request_count,
        }
        
        if include_internal:
            result["_table_name"] = self.table_name
        
        return result


class LogicalSchemaTransformer:
    """
    Transforms physical MapRegister structure into logical entity definitions.
    Hides all backend-specific details from the frontend.
    """
    
    # Mapping from Metadata types to user-friendly logical types
    TYPE_MAPPING = {
        "int": "integer",
        "float": "decimal",
        "bool": "boolean",
        "str": "string",
        "list": "array",
        "dict": "object",
        "UNK": "unknown",
    }
    
    def __init__(self):
        self.entities: Dict[str, LogicalEntity] = {}
        logger.info("LogicalSchemaTransformer initialized")
    
    def transform_map_register(self, register: Any) -> Optional[LogicalEntity]:
        """
        Transform a MapRegister into a LogicalEntity.
        
        Args:
            register: MapRegister instance from app.state.map_register
        
        Returns:
            LogicalEntity with abstracted schema
        """
        if not hasattr(register, "table_name") or not hasattr(register, "map"):
            logger.warning("Invalid MapRegister structure")
            return None
        
        # Create entity with user-friendly name (singular, PascalCase)
        logical_name = self._humanize_table_name(register.table_name)
        entity = LogicalEntity(logical_name, register.table_name)
        entity.request_count = getattr(register, "request_count", 0)
        
        # Transform fields from Metadata
        for field_name, metadata in register.map.items():
            if not hasattr(metadata, "type"):
                continue
            
            # Skip internal autogenerated fields from UI
            if field_name == "table_autogen_id":
                continue
            
            field = LogicalField(
                name=field_name,
                logical_type=self.TYPE_MAPPING.get(metadata.type, "unknown"),
            )
            
            # Mark primary keys and auto-generated fields
            if field_name.endswith("_id") or field_name == "id":
                field.is_key = True
            
            if hasattr(metadata, "auto") and metadata.auto:
                field.is_auto_generated = True
            
            # Sample value from current_value
            if hasattr(metadata, "current_value"):
                field.sample_value = metadata.current_value
            
            entity.add_field(field)
        
        # Add foreign key relationships
        if hasattr(register, "foreign_key_refs"):
            fk_refs = register.foreign_key_refs or {}
            for nested_field, ref_meta in fk_refs.items():
                if isinstance(ref_meta, dict):
                    child_table = ref_meta.get("child_table")
                    if child_table:
                        child_entity_name = self._humanize_table_name(child_table)
                        entity.add_relationship(child_entity_name, "one_to_many")
        
        # Store for future reference
        self.entities[logical_name] = entity
        
        logger.info(f"Transformed MapRegister '{register.table_name}' → LogicalEntity '{logical_name}'")
        
        return entity
    
    def get_logical_entity(self, entity_name: str) -> Optional[LogicalEntity]:
        """Retrieve a logical entity by name."""
        return self.entities.get(entity_name)
    
    def get_all_entities(self) -> List[Dict[str, Any]]:
        """Get all logical entities (without backend details)."""
        return [entity.to_dict() for entity in self.entities.values()]
    
    def get_entity_schema(self, entity_name: str) -> Optional[Dict[str, Any]]:
        """Get schema for a specific entity (hiding backend details)."""
        entity = self.get_logical_entity(entity_name)
        if not entity:
            return None
        return entity.to_dict(include_internal=False)
    
    def get_entity_from_table_name(self, table_name: str) -> Optional[LogicalEntity]:
        """Internal method: Get entity by internal table name."""
        for entity in self.entities.values():
            if entity.table_name == table_name:
                return entity
        return None
    
    def update_record_count(self, entity_name: str, count: int) -> None:
        """Update record count for an entity (called after fetch operations)."""
        entity = self.get_logical_entity(entity_name)
        if entity:
            entity.record_count = count
    
    def _humanize_table_name(self, table_name: str) -> str:
        """
        Convert internal table name to user-friendly entity name.
        
        Examples:
            users → User
            user_accounts → UserAccount
            user_profile_data → UserProfileData
        """
        # Split by underscore and capitalize each word
        parts = table_name.split("_")
        entity_name = "".join(word.capitalize() for word in parts)
        
        # Remove trailing 's' for plurals (users → User)
        if entity_name.endswith("s") and len(entity_name) > 1:
            # Only remove if not a word like "Status"
            if not entity_name.endswith("ss"):
                entity_name = entity_name[:-1]
        
        return entity_name
    
    def _reverse_humanize_name(self, entity_name: str) -> str:
        """
        Convert entity name back to table name format (for internal lookups).
        This is primarily for debugging/logging.
        
        Examples:
            User → users
            UserAccount → user_accounts
        """
        result = []
        for i, char in enumerate(entity_name):
            if i > 0 and char.isupper():
                result.append("_")
                result.append(char.lower())
            else:
                result.append(char.lower())
        return "".join(result) + "s"  # Add plural
    
    def clear_cache(self) -> None:
        """Clear cached entities."""
        self.entities.clear()
        logger.info("Logical schema cache cleared")
